import React, { Component } from "react";
// import * as Icon from "react-feather";
// import { Link } from "react-router-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faLightbulb,
  faPaperPlane,
  faUserCircle,
  faMap,
  faComments
} from "@fortawesome/free-solid-svg-icons";

class Services extends Component {
  render() {
    return (
      <section className="iot-services-area ptb-80">
        <div className="container">
          {/* <div className="section-title">
                <h3>About Plan A Trip</h3>
                <div className="bar"></div>
                <p>Fun, fast, free travel planning. Plan A Trip is the first travel platform where you can do all your travel planning in one place. Go on an adventure. Leave the rest to us</p>
            </div> */}

          <div className="row">
            <div className="col-lg-4 col-md-6">
              <div className="single-repair-services bg1">
                <div className="icon">
                  <FontAwesomeIcon icon={faLightbulb} />
                </div>

                <h3>
                  Discover
                  <br />
                </h3>
                <p>Explore places that match your interests </p>

                {/* <Link to={`/explore`}>
                  <Icon.ArrowRight />
                </Link> */}
              </div>
            </div>

            <div className="col-lg-4 col-md-6">
              <div className="single-repair-services bg2">
                <div className="icon">
                  <FontAwesomeIcon icon={faMap} />
                </div>

                <h3>Browse travel plans</h3>
                <p>
                  Whether generated by AI or an actual travel expert, we have
                  plans for every type of travelers
                </p>

                {/* <Link to={`/explore`}>
                  <Icon.ArrowRight />
                </Link> */}
              </div>
            </div>

            <div className="col-lg-4 col-md-6">
              <div className="single-repair-services bg4">
                <div className="icon">
                  <FontAwesomeIcon icon={faUserCircle} />
                </div>

                <h3>Share love with the community</h3>
                <p>
                  Think you have a better plan? Share your journey and benefits
                  the travel community. Don't worry, you can adjust your privacy
                  settings in your profile so we only share what you meant to
                  share.{" "}
                </p>

                {/* <Link to={`/`}>
                  <Icon.ArrowRight />
                </Link> */}
              </div>
            </div>

            <div className="col-lg-4 col-md-6">
              <div className="single-repair-services bg5">
                <div className="icon">
                  <FontAwesomeIcon icon={faPaperPlane} />
                </div>

                <h3>
                  Bookings <br />
                  Coming soon
                </h3>
                <p>
                  {" "}
                  Browse things to do while we are working on a full-fledge
                  bookings from flights, air-port pickup, activities, hotels,
                  restaurants, and anything else you can dream of.{" "}
                </p>
                {/* 
                <Link to={`/tours`}>
                  <Icon.ArrowRight />
                </Link> */}
              </div>
            </div>

            <div className="col-lg-4 col-md-6">
              <div className="single-repair-services bg3">
                <div className="icon">
                  <FontAwesomeIcon icon={faComments} />
                </div>

                <h3>
                  Ask a friend <br /> Coming soon
                </h3>
                <p>
                  Feeling hesitant? Use the social media feature to seek advice.
                  You can even greet and meet new friends who's been to your
                  location of interest.
                </p>

                {/* <Link to={`/`}>
                  <Icon.ArrowRight />
                </Link> */}
              </div>
            </div>
          </div>
        </div>
      </section>
    );
  }
}

export default Services;
